# Generated by Django 4.2.2 on 2023-06-20 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('BirthDate', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Publication_Date', models.DateField()),
                ('Created_Date', models.DateField(auto_now_add=True)),
                ('Is_Available', models.BooleanField(default=True)),
                ('Price', models.FloatField()),
                ('Description', models.TextField()),
                ('Book_Code', models.CharField(max_length=15)),
                ('Rating', models.FloatField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryApp.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryApp.category')),
                ('genre', models.ManyToManyField(to='libraryApp.genre')),
            ],
        ),
    ]
